Update rules.tsx
quick007/quartzstudios.net pull request #3
Opened 2021-05-10 08:29 UTC by MiginsMC

2021-05-10 16:07 UTC, quick007 requested changes
Looks great besides the few comments I made!

2021-05-10 16:07 UTC, quick007 commented on pages/resources/rules.tsx
> +                                    <li className="w-full md:w-[95%] px-3 py-4 bg-gray-800 rounded">Purposely misusing channels on the Discord is not allowed. If you are unsure of a channel’s usage,
I actually said didn't add "in the discord" in purpose in case we added like "channels" ingame

2021-05-10 16:07 UTC, quick007 commented on pages/resources/rules.tsx
> +                                    <li className="w-full md:w-[95%] px-3 py-4 bg-gray-800 rounded">Exploiting vanilla Mincraft exploits or unintentional "features" in our custom systems is not allow
didn't fix the whole reason we had the pr lol (minecraft misspelled)

2021-05-10 16:07 UTC, quick007 commented on pages/resources/rules.tsx
> +                                    <li className="w-full md:w-[95%] px-3 py-4 bg-gray-800 rounded">Threatening to DDoS, DoS, dox, kill or otherwise harm someone with malicious intent is not allowed.
You could add "Threatening to or actually..."

2021-05-10 21:07 UTC, MiginsMC commented on pages/resources/rules.tsx
> +                                    <li className="w-full md:w-[95%] px-3 py-4 bg-gray-800 rounded">Threatening to DDoS, DoS, dox, kill or otherwise harm someone with malicious intent is not allowed.
I mean literally killing someone irl puts them in trouble with the law i dont think we really need to moderate further then that. wouldnt be opposed to having that for doxxing tho

2021-05-10 22:05 UTC, quick007 commented on pages/resources/rules.tsx
> +                                    <li className="w-full md:w-[95%] px-3 py-4 bg-gray-800 rounded">Threatening to DDoS, DoS, dox, kill or otherwise harm someone with malicious intent is not allowed.
true

2021-05-10 23:26 UTC, quick007 approved these changes
I just went ahead and updated what I commented, this looks good otherwise, I'll merge it to dev

2021-05-10 23:27 UTC, merged

2021-05-11 04:47 UTC, MiginsMC commented
ok doki cooliosis